#ifndef GBUFFER_ATTRIBUTE_SLOTS_HLSL
#define GBUFFER_ATTRIBUTE_SLOTS_HLSL


#define ATT_SLOT_UV                 0
#define ATT_SLOT_TANGENT_VIEW       1
#define ATT_SLOT_BITANGENT_VIEW     2
#define ATT_SLOT_NORMAL_VIEW        3
#define ATT_SLOT_INSTANCE_ID        4


#endif // GBUFFER_ATTRIBUTE_SLOTS_HLSL
