#ifndef HTML_VALIDATOR_VERSION_HPP
#define HTML_VALIDATOR_VERSION_HPP


#define HTML_VALIDATOR_VERSION_MAJOR        1
#define HTML_VALIDATOR_VERSION_MINOR        0
#define HTML_VALIDATOR_VERSION_RELEASE      1
#define HTML_VALIDATOR_VERSION_BUILD        10


#endif // HTML_VALIDATOR_VERSION_HPP
