#ifndef EXPOSURE_INC
#define EXPOSURE_INC


#define CONST_WORKGROUP_COUNT       0

#define CONST_MIP_5_W               1
#define CONST_MIP_5_H               2
#define CONST_NORMALIZE_W           3
#define CONST_NORMALIZE_H           4

#define SET_RESOURCE                0
#define BIND_HDR_IMAGE              0
#define BIND_SYNC_MIP_5             1
#define BIND_EXPOSURE               2
#define BIND_GLOBAL_ATOMIC          3
#define BIND_TEMPORAL_LUMA          4


#endif // EXPOSURE_INC
