#ifndef LIGHTUP_COMMON_INC
#define LIGHTUP_COMMON_INC


#define SET_COMMON                  0
#define BIND_ALBEDO_TEXTURE         0
#define BIND_NORMAL_TEXTURE         1
#define BIND_PARAMS_TEXTURE         2
#define BIND_DEPTH_TEXTURE          3
#define BIND_BRDF_TEXTURE           4
#define BIND_BRDF_SAMPLER           5
#define BIND_PREFILTER_SAMPLER      6
#define BIND_VIEW_DATA              7


#endif // LIGHTUP_COMMON_INC
