#ifndef SPD_INC
#define SPD_INC


#define CONST_WORKGROUP_COUNT       0

#define CONST_MIP_5_W               1
#define CONST_MIP_5_H               2
#define CONST_MIP_6_W               3
#define CONST_MIP_6_H               4
#define CONST_MIP_7_W               5
#define CONST_MIP_7_H               6
#define CONST_MIP_8_W               7
#define CONST_MIP_8_H               8
#define CONST_MIP_9_W               9
#define CONST_MIP_9_H               10

#define SET_RESOURCE                0
#define BIND_HDR_IMAGE              0
#define BIND_SYNC_MIP_5             1
#define BIND_MIPS                   2
#define BIND_GLOBAL_ATOMIC          3
#define BIND_BRIGHTNESS             4


#endif // SPD_INC
