#ifndef UI_PROGRAM_INC
#define UI_PROGRAM_INC


#define IN_SLOT_VERTEX          0
#define IN_SLOT_COLOR           1
#define IN_SLOT_ATLAS           2
#define IN_SLOT_IMAGE_UV        3

#define ATT_SLOT_COLOR          0
#define ATT_SLOT_ATLAS_UV       1
#define ATT_SLOT_ATLAS_LAYER    2
#define ATT_SLOT_IMAGE_UV       3

#define BIND_TRANSFORM          0
#define SET_TRANSFORM           0

#define BIND_ATLAS_SAMPLER      1
#define SET_ATLAS_SAMPLER       0

#define BIND_ATLAS_TEXTURE      2
#define SET_ATLAS_TEXTURE       0

#define BIND_IMAGE_SAMPLER      3
#define SET_IMAGE_SAMPLER       0

#define BIND_IMAGE_TEXTURE      0
#define SET_IMAGE_TEXTURE       1


#endif // UI_PROGRAM_INC
