#ifndef UI_PROGRAM_INC
#define UI_PROGRAM_INC


#define IN_BUFFER_POSITION                              0
#define IN_SLOT_POSITION                                0

#define IN_BUFFER_REST                                  1
#define IN_SLOT_IMAGE_UV                                1
#define IN_SLOT_ATLAS_LAYER_AND_UI_PRIMITIVE_TYPE       2
#define IN_SLOT_COLOR                                   3

#define ATT_SLOT_UV                                     0
#define ATT_SLOT_ATLAS_LAYER                            1
#define ATT_SLOT_UI_PRIMITIVE_TYPE                      2
#define ATT_SLOT_COLOR                                  3

#define SET_TRANSFORM                                   0
#define BIND_TRANSFORM                                  0

#define SET_COMMON                                      1
#define BIND_ATLAS_SAMPLER                              0
#define BIND_ATLAS_TEXTURE                              1
#define BIND_TEXT_LUT_SAMPLER                           2
#define BIND_TEXT_LUT_TEXTURE                           3
#define BIND_IMAGE_SAMPLER                              4

#define SET_IMAGE_TEXTURE                               2
#define BIND_IMAGE_TEXTURE                              0


#endif // UI_PROGRAM_INC
