#ifndef BINDINGS_INC
#define BINDINGS_INC


#define IN_BUFFER_POSITION              0
#define IN_SLOT_POSITION                0

#define IN_BUFFER_REST                  1
#define IN_SLOT_UV                      1
#define IN_SLOT_TBN                     2

#define ATT_SLOT_FRAGMENT_VIEW          0
#define ATT_SLOT_UV                     1
#define ATT_SLOT_NORMAL_VIEW            2
#define ATT_SLOT_TANGENT_VIEW           3
#define ATT_SLOT_BITANGENT_VIEW         4

#define SET_FIXED                       0
#define BIND_SAMPLER                    0

#define SET_ONCE                        1
#define BIND_TRANSFORM                  0

#define SET_MATERIAL                    2
#define BIND_DIFFUSE_TEXTURE            0
#define BIND_NORMAL_TEXTURE             1
#define BIND_LUT_TEXTURE                2


#endif // BINDINGS_INC
