/* This file is automatically generated by the DailyBuild script. */
#if 0
// just a dummy section to make the file more like the generated one from the build maching
// note:  if the format of this file changes dramatically, you will have to change 
// CSharpVersionWriter in BuildTools, as we use it to generate src\include\dotNet\AssemblyVersion.cs
// for C# projects
#else // MAX
  #define VERSION_STRING  "Vesta with PDBs V997_RL_x64 02-18-2022 14:12 de50ca731d3828474ff4ed22eec2de76488a73f6"
  #define VERSION_INT   997
#endif

